#!/bin/bash
while read P1
do
./gppk p dpp/${P1}.dpp
mv lps/${P1}.lp lps/${P1}_p.lp
./gppk mcf dpp/${P1}.dpp
mv lps/${P1}.lp lps/${P1}_mcf.lp
echo "Job for ${P1} submitted on `date`"
done < std_inst.txt
exit
