#!/bin/bash
#export DIR=/Home/siv13/mal025/phdstuff/phdpapers/paper4/tables/
#date
#./printgams hrs1
#cp hrs1model_inst_prob.tab $DIR/hrspq_prob.tab 
#cp hrs1model_inst_sol.tab $DIR/hrspq_sol.tab
#./printgams hrs
#cp hrsmodel_inst_prob.tab $DIR/hrspq_prob_alt.tab 
#cp hrsmodel_inst_sol.tab $DIR/hrspq_sol_alt.tab
#date

date 
./printgppk hrs pq
mv *.tab pq/.
date
./printgppk hrs p
mv *.tab p/.
date

cd ../gamsfiles
./printgams hrs
echo 'HRS with MCF finished'
date
./printgams hrsp
echo 'HRS with P finished'
date
./printgams mlt
echo 'GAMS Multi-start finished'